[project]
name = "fastapi-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.17.2",
    "anthropic>=0.74.0",
    "asyncpg>=0.31.0",
    "chromadb>=0.4.22",
    "fastapi>=0.121.2",
    "firecrawl-py>=1.5.0",
    "langchain>=1.0.7",
    "langchain-anthropic>=0.3.5",
    "langchain-google-genai>=3.0.3",
    "langchain-groq>=0.2.1",
    "langchain-openai>=0.3.0",
    "langgraph>=1.0.3",
    "psycopg2-binary>=2.9.11",
    "pydantic-settings>=2.12.0",
    "pyjwt[crypto]>=2.8.0",
    "redis>=5.0.1",
    "sqlmodel>=0.0.27",
    "uvicorn[standard]>=0.38.0",
]
